# ##############################################################################
# vendor/HelmOne/boards/sf32lb52/helmone/domain/CMakeLists.txt
#
# Layer: domain libraries (GPX, fonts, EPIC stubs).
#
# SPDX-License-Identifier: Apache-2.0
# ##############################################################################

add_subdirectory(gpx)
add_subdirectory(lvgl_font)
add_subdirectory(lvgl_epic)
