/**
 * @file NaviArrow.h
 * @brief 生成/位图资源数据。
 */

/*
 * NaviArrow — compiled-in (C-array) navigation arrow images, managed by a
 * small style-indexed table so swapping or adding an arrow style later is a
 * one-line change (add the generated descriptor + an array entry + an enum).
 *
 * The pixel data lives in flash (lv_pm/img/img_src_navi_arrow_*.c), so the
 * arrow is always available without PNG decoding or LVGL image-cache pressure.
 */
#ifndef __NAVI_ARROW_H
#define __NAVI_ARROW_H

#include "lvgl/lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* generated by scripts/LVGLImage.py from mkfs/images/navi_arrow_*.png */
extern const lv_image_dsc_t img_src_navi_arrow_light;
extern const lv_image_dsc_t img_src_navi_arrow_dark;

typedef enum {
    NAVI_ARROW_LIGHT = 0,
    NAVI_ARROW_DARK,
    NAVI_ARROW_STYLE_COUNT
} navi_arrow_style_t;

/* Descriptor for a style (out-of-range clamps to NAVI_ARROW_LIGHT). Pass the
 * result straight to lv_img_set_src() / MapView::addArrowImage(). */
const lv_image_dsc_t* navi_arrow_get(navi_arrow_style_t style);

#ifdef __cplusplus
}
#endif

#endif /* __NAVI_ARROW_H */
