/**
 * @file fs_procfs_mount.c
 * @brief 板级抽换 `nuttx/fs/mount/fs_procfs_mount.c`：`df -h` 用 64 位乘法。
 *
 * CMake 从 lib `fs` 去掉上游同名源，改编本文件。相对上游：
 * `/proc/fs/usage`（`df -h`）用 `uint64_t` 计算 `f_bsize * f_blocks`，
 * 避免 ≥ 4 GiB 的 LittleFS 窗口 wrap 成 2032 MiB。
 *
 * 不修改 `nuttx/` 树。见 `docs/sd_partition.md` 第 5 节。
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>

/* ---- 抽换件标记（2026-09-18）----------------------------------------------
 * 1) 构建日志里可见：`ninja | grep "override compiled"` 能列出本次构建真的编译了
 *    哪些抽换件 —— 2026-09-18 曾有个抽换件其实根本不在编译库里（已剔除），
 *    改了半天没生效，就靠这种标记一眼看出来；
 * 2) 镜像里可查：`strings nuttx | grep vela_override/`（本符号 used，不会被
 *    --gc-sections 丢掉），不依赖任何编译选项（有些目标带 -w，会把 #warning 压掉）。
 * 见 docs/pitch/README.md。 */
/* ---------------------------------------------------------------------------
 * 抽换件说明（vela_override）
 *   替的是上游 : nuttx / fs/mount/fs_procfs_mount.c
 *   写入时 HEAD: 2ce740a0ac1052c5f51083a334ef3093f59ff780
 *   上游 blob  : 86004c0e59e594d3234e1cd705614ca5d3aaa530     （git -C nuttx rev-parse HEAD:fs/mount/fs_procfs_mount.c 应等于它）
 *   为什么抽换 : df -h 用 uint64，避免 >=4GiB wrap
 *   版本漂移自查:
 *     git -C nuttx rev-parse HEAD:fs/mount/fs_procfs_mount.c   # 与上面的 blob 比对
 *     git -C nuttx diff -- fs/mount/fs_procfs_mount.c          # 上游若已前进，先看这里再决定还要不要抽换
 *   机制：构建时按**文件名**把这个 .c 顶掉上游同名文件（见同目录 CMakeLists.txt 顶部表），
 *         上游 tree 保持干净、repo sync 收不走 —— 所以本文件不进 docs/pitch。
 * ------------------------------------------------------------------------- */
#pragma message("myvendor override compiled: vela_override/fs/fs_procfs_mount.c -- 上游 nuttx:fs/mount/fs_procfs_mount.c@86004c0e59e5 -- df -h 用 uint64，避免 >=4GiB wrap")
const char myvendor_override_marker_fs_fs_procfs_mount_c[] __attribute__((used, section(".myvendor_marker"))) = "vela_override/fs/fs_procfs_mount.c -- 上游 nuttx:fs/mount/fs_procfs_mount.c@86004c0e59e5 -- df -h 用 uint64，避免 >=4GiB wrap";
#include <nuttx/compiler.h>

#include <inttypes.h>
#include <sys/types.h>
#include <sys/statfs.h>
#include <sys/stat.h>

#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <assert.h>
#include <errno.h>
#include <debug.h>

#include <nuttx/kmalloc.h>
#include <nuttx/fs/fs.h>
#include <nuttx/fs/procfs.h>

#include "mount/mount.h"
#include "fs_heap.h"

#if !defined(CONFIG_DISABLE_MOUNTPOINT) && defined(CONFIG_FS_PROCFS)
#if !defined(CONFIG_FS_PROCFS_EXCLUDE_MOUNT) || \
    !defined(CONFIG_FS_PROCFS_EXCLUDE_BLOCKS) || \
    !defined(CONFIG_FS_PROCFS_EXCLUDE_USAGE)

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* Determines the size of an intermediate buffer that must be large enough
 * to handle the longest line generated by this logic.
 */

#define MOUNT_LINELEN 64

/****************************************************************************
 * Private Types
 ****************************************************************************/

enum mount_file_e
{
  FS_MOUNT_FILE = 0,                 /* /proc/fs/mount */
  FS_BLOCKS_FILE,                    /* /proc/fs/blocks */
  FS_USAGE_FILE,                     /* /proc/fs/usage */
};

struct mount_file_s
{
  struct procfs_file_s base;         /* Base open file structure */
  uint8_t id;                        /* See enum mount_file_e */
  char line[MOUNT_LINELEN];          /* Pre-allocated buffer for formatted lines */
};

/* The structure is used when traversing routing tables */

struct mount_info_s
{
  FAR char *line;                    /* Intermediate line buffer pointer */
  FAR char *buffer;                  /* User buffer */
  size_t    linelen;                 /* Size of the intermediate buffer */
  size_t    buflen;                  /* Size of the user buffer */
  size_t    remaining;               /* Bytes remaining in user buffer */
  size_t    totalsize;               /* Accumulated size of the copy */
  off_t     offset;                  /* Skip offset */
  bool      header;                  /* True: header has been generated */
};

/****************************************************************************
 * Private Function Prototypes
 ****************************************************************************/

/* Helpers */

static void    mount_sprintf(FAR struct mount_info_s *info,
                             FAR const char *fmt, ...) printf_like(2, 3);
#ifndef CONFIG_FS_PROCFS_EXCLUDE_MOUNT
static int     mount_entry(FAR const char *mountpoint,
                           FAR struct statfs *statbuf, FAR void *arg);
#endif
#ifndef CONFIG_FS_PROCFS_EXCLUDE_BLOCKS
static int     blocks_entry(FAR const char *mountpoint,
                            FAR struct statfs *statbuf, FAR void *arg);
#endif
#ifndef CONFIG_FS_PROCFS_EXCLUDE_USAGE
static int     usage_entry(FAR const char *mountpoint,
                           FAR struct statfs *statbuf, FAR void *arg);
#endif

/* File system methods */

static int     mount_open(FAR struct file *filep, FAR const char *relpath,
                          int oflags, mode_t mode);
static int     mount_close(FAR struct file *filep);
static ssize_t mount_read(FAR struct file *filep, FAR char *buffer,
                          size_t buflen);

/****************************************************************************
 * Public Data
 ****************************************************************************/

/* See fs_mount.c -- this structure is explicitly externed there.
 * We use the old-fashioned kind of initializers so that this will compile
 * with any compiler.
 */

const struct procfs_operations g_mount_operations =
{
  mount_open,          /* open */
  mount_close,         /* close */
  mount_read,          /* read */
};

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: mount_sprintf
 *
 * Description:
 *   Generate otuput from fs/mount, fs/blocks, or fs/usage, file read.
 *
 ****************************************************************************/

static void mount_sprintf(FAR struct mount_info_s *info,
                          FAR const char *fmt, ...)
{
  size_t linesize;
  size_t copysize;
  va_list ap;

  /* Print the format and data to a line buffer */

  va_start(ap, fmt);
  linesize = vsnprintf(info->line, info->linelen, fmt, ap);
  va_end(ap);

  /* Copy the line buffer to the user buffer */

  copysize = procfs_memcpy(info->line, linesize,
                           info->buffer, info->remaining,
                           &info->offset);

  /* Update counts and pointers */

  info->totalsize += copysize;
  info->buffer    += copysize;
  info->remaining -= copysize;
}

/****************************************************************************
 * Name: mount_entry
 *
 * Description:
 *   Output one fs/mount entry
 *
 *   Format:
 *     <mountpoint> type <type>
 *
 ****************************************************************************/

#ifndef CONFIG_FS_PROCFS_EXCLUDE_MOUNT
static int mount_entry(FAR const char *mountpoint,
                       FAR struct statfs *statbuf, FAR void *arg)
{
  FAR struct mount_info_s *info = (FAR struct mount_info_s *)arg;
  FAR const char *fstype;

  DEBUGASSERT(mountpoint != NULL && statbuf != NULL && info != NULL);

  /* Get the file system type */

  fstype = fs_gettype(statbuf);

  /* Generate mount list one line at a time */

  mount_sprintf(info, "  %s type %s\n", mountpoint, fstype);
  return (info->totalsize >= info->buflen) ? 1 : 0;
}
#endif

/****************************************************************************
 * Name: blocks_entry
 *
 * Description:
 *   Output one fs/blocks entry
 *
 *   Format:
 *     <mountpoint> type <type>
 *
 ****************************************************************************/

#ifndef CONFIG_FS_PROCFS_EXCLUDE_BLOCKS
static int blocks_entry(FAR const char *mountpoint,
                        FAR struct statfs *statbuf, FAR void *arg)
{
  FAR struct mount_info_s *info = (FAR struct mount_info_s *)arg;

  DEBUGASSERT(mountpoint != NULL && statbuf != NULL && info != NULL);

  /* Have we generated the header yet? */

  if (!info->header)
    {
      mount_sprintf(info,
                    "  Block    Number\n");
      mount_sprintf(info,
                    "  Size     Blocks       Used   Available Mounted on\n");
      info->header = true;
    }

  /* Generate blocks list one line at a time */

  mount_sprintf(info, "%6zu %10" PRIuOFF " %10" PRIuOFF
                "  %10" PRIuOFF " %s\n",
                statbuf->f_bsize, statbuf->f_blocks,
                statbuf->f_blocks - statbuf->f_bavail, statbuf->f_bavail,
                mountpoint);

  return (info->totalsize >= info->buflen) ? 1 : 0;
}
#endif

/****************************************************************************
 * Name: blocks_entry
 *
 * Description:
 *   Output one fs/usage entry
 *
 *   Format:
 *     <mountpoint> type <type>
 *
 ****************************************************************************/

#ifndef CONFIG_FS_PROCFS_EXCLUDE_USAGE
/**
 * @brief 把字节数收成最多 4 位系数加单位（B/K/M/G/T）。
 *
 * 必须用 `uint64_t`：`f_bsize * f_blocks` 在约 14 GiB 窗口上会溢出 32 位
 *（3665920 × 4096 = 15015608320，wrap 成 2032 MiB）。
 *
 * @param bytes 容量字节数。
 * @param[out] label 写入一个单位字符（`B`/`K`/`M`/`G`/`T`）。
 * @return 该单位下的系数。
 */
static uint64_t mount_humanize(uint64_t bytes, FAR char *label)
{
  static const char labels[5] =
  {
    'B', 'K', 'M', 'G', 'T'
  };
  int which = 0;

  while (which < 4 &&
         (bytes >= 10240 || ((bytes & 0x3ff) == 0 && bytes != 0)))
    {
      which++;
      if (bytes >= 10240)
        {
          bytes = (bytes + 512) >> 10;
        }
      else
        {
          bytes >>= 10;
        }
    }

  *label = labels[which];
  return bytes;
}

static int usage_entry(FAR const char *mountpoint,
                       FAR struct statfs *statbuf, FAR void *arg)
{
  FAR struct mount_info_s *info = (FAR struct mount_info_s *)arg;
  FAR const char *fstype;
  uint64_t size;
  uint64_t used;
  uint64_t avail;
  char sizelabel;
  char freelabel;
  char usedlabel;

  DEBUGASSERT(mountpoint != NULL && statbuf != NULL && info != NULL);

  /* Have we generated the header yet? */

  if (!info->header)
    {
      mount_sprintf(info,
        "  Filesystem      Size      Used  Available Mounted on\n");
      info->header = true;
    }

  /* Get the file system type */

  fstype = fs_gettype(statbuf);

  size  = (uint64_t)statbuf->f_bsize * (uint64_t)statbuf->f_blocks;
  avail = (uint64_t)statbuf->f_bsize * (uint64_t)statbuf->f_bavail;
  used  = size - avail;

  size  = mount_humanize(size, &sizelabel);
  used  = mount_humanize(used, &usedlabel);
  avail = mount_humanize(avail, &freelabel);

  /* Generate usage list one line at a time */

  mount_sprintf(info,
    "  %-10s %8lu%c %8lu%c  %8lu%c %s\n",
    fstype,
    (unsigned long)size, sizelabel,
    (unsigned long)used, usedlabel,
    (unsigned long)avail, freelabel, mountpoint);

  return (info->totalsize >= info->buflen) ? 1 : 0;
}
#endif

/****************************************************************************
 * Name: mount_open
 ****************************************************************************/

static int mount_open(FAR struct file *filep, FAR const char *relpath,
                      int oflags, mode_t mode)
{
  FAR struct mount_file_s *procfile;
  uint8_t id;

  finfo("Open '%s'\n", relpath);

  /* PROCFS is read-only.  Any attempt to open with any kind of write
   * access is not permitted.
   *
   * REVISIT:  Write-able proc files could be quite useful.
   */

  if ((oflags & O_WRONLY) != 0 || (oflags & O_RDONLY) == 0)
    {
      ferr("ERROR: Only O_RDONLY supported\n");
      return -EACCES;
    }

  /* "fs/mount", "fs/block", and "fs/usage" are the only acceptable values
   * for the relpath.
   */

#ifndef CONFIG_FS_PROCFS_EXCLUDE_MOUNT
  if (strcmp(relpath, "fs/mount") == 0)
    {
      id = FS_MOUNT_FILE;
    }
#endif
#ifndef CONFIG_FS_PROCFS_EXCLUDE_BLOCKS
  else if (strcmp(relpath, "fs/blocks") == 0)
    {
      id = FS_BLOCKS_FILE;
    }
#endif
  else if (strcmp(relpath, "fs/usage") == 0)
    {
      id = FS_USAGE_FILE;
    }
  else
    {
      ferr("ERROR: relpath is '%s'\n", relpath);
      return -ENOENT;
    }

  /* Allocate a container to hold the task and node selection */

  procfile = (FAR struct mount_file_s *)
    fs_heap_zalloc(sizeof(struct mount_file_s));
  if (!procfile)
    {
      ferr("ERROR: Failed to allocate file container\n");
      return -ENOMEM;
    }

  /* Save the file ID */

  procfile->id = id;

  /* Save the open-specific state in filep->f_priv */

  filep->f_priv = (FAR void *)procfile;
  return OK;
}

/****************************************************************************
 * Name: mount_close
 ****************************************************************************/

static int mount_close(FAR struct file *filep)
{
  FAR struct mount_file_s *procfile;

  /* Recover our private data from the struct file instance */

  procfile = (FAR struct mount_file_s *)filep->f_priv;
  DEBUGASSERT(procfile);

  /* Release the file container structure */

  fs_heap_free(procfile);
  filep->f_priv = NULL;
  return OK;
}

/****************************************************************************
 * Name: mount_read
 ****************************************************************************/

static ssize_t mount_read(FAR struct file *filep, FAR char *buffer,
                          size_t buflen)
{
  FAR struct mount_file_s *procfile;
  struct mount_info_s info;
  foreach_mountpoint_t handler;
  ssize_t ret;

  finfo("buffer=%p buflen=%d\n", buffer, (int)buflen);

  /* Recover our private data from the struct file instance */

  procfile = (FAR struct mount_file_s *)filep->f_priv;
  DEBUGASSERT(procfile);

  /* Provide the requested data */

  memset(&info, 0, sizeof(struct mount_info_s));
  info.line      = procfile->line;
  info.buffer    = buffer;
  info.linelen   = MOUNT_LINELEN;
  info.buflen    = buflen;
  info.remaining = buflen;
  info.offset    = filep->f_pos;
  info.header    = false;

  switch (procfile->id)
    {
#ifndef CONFIG_FS_PROCFS_EXCLUDE_MOUNT
      case FS_MOUNT_FILE:                 /* /proc/fs/mount */
        handler = mount_entry;
        break;
#endif

#ifndef CONFIG_FS_PROCFS_EXCLUDE_BLOCKS
      case FS_BLOCKS_FILE:                /* /proc/fs/blocks */
        handler = blocks_entry;
        break;
#endif

#ifndef CONFIG_FS_PROCFS_EXCLUDE_USAGE
      case FS_USAGE_FILE:                 /* /proc/fs/usage */
        handler = usage_entry;
        break;
#endif

      default:
        DEBUGPANIC();
        return -EINVAL;
    }

  /* Generate each entry in the routing table */

  foreach_mountpoint(handler, &info);
  ret = info.totalsize;

  /* Update the file offset */

  if (ret > 0)
    {
      filep->f_pos += ret;
    }

  return ret;
}

#endif /* !CONFIG_FS_PROCFS_EXCLUDE_MOUNT || \
        * !CONFIG_FS_PROCFS_EXCLUDE_BLOCKS || \
        * !CONFIG_FS_PROCFS_EXCLUDE_USAGE */
#endif /* !CONFIG_DISABLE_MOUNTPOINT && CONFIG_FS_PROCFS */
